// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	constants "github.com/MorZLE/metrick/internal/client/constants"

	mock "github.com/stretchr/testify/mock"
)

// HandleRequest is an autogenerated mock type for the HandleRequest type
type HandleRequest struct {
	mock.Mock
}

// Request provides a mock function with given fields: obj, port
func (_m *HandleRequest) Request(obj constants.Metrics, port string) {
	_m.Called(obj, port)
}

type mockConstructorTestingTNewHandleRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewHandleRequest creates a new instance of HandleRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHandleRequest(t mockConstructorTestingTNewHandleRequest) *HandleRequest {
	mock := &HandleRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
