// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HandlerServer is an autogenerated mock type for the HandlerServer type
type HandlerServer struct {
	mock.Mock
}

// UpServer provides a mock function with given fields:
func (_m *HandlerServer) UpServer() {
	_m.Called()
}

// UpdateMetric provides a mock function with given fields: res, req
func (_m *HandlerServer) UpdateMetric(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// routs provides a mock function with given fields:
func (_m *HandlerServer) routs() {
	_m.Called()
}

type mockConstructorTestingTNewHandlerServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewHandlerServer creates a new instance of HandlerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHandlerServer(t mockConstructorTestingTNewHandlerServer) *HandlerServer {
	mock := &HandlerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
